import AnimationComponent from '../components/AnimationComponent';
import BoxColliderComponent from '../components/BoxColliderComponent';
import CameraFollowComponent from '../components/CameraFollowComponent';
import CameraShakeComponent from '../components/CameraShakeComponent';
import DamageRadiusComponent from '../components/DamageRadiusComponent';
import DeadBodyOnDeathComponent from '../components/DeadBodyOnDeathComponent';
import EntityDestinationComponent from '../components/EntityDestinationComponent';
import EntityEffectComponent from '../components/EntityEffectComponent';
import EntityFollowComponent from '../components/EntityFollowComponent';
import HealthComponent from '../components/HealthComponent';
import HighlightComponent from '../components/HighlightComponent';
import LifetimeComponent from '../components/LifetimeComponent';
import LightEmitComponent from '../components/LightEmitComponent';
import ParticleComponent from '../components/ParticleComponent';
import ParticleEmitComponent from '../components/ParticleEmitComponent';
import PlayerControlComponent from '../components/PlayerControlComponent';
import ProjectileComponent from '../components/ProjectileComponent';
import RangedAttackEmitterComponent from '../components/RangedAttackEmitterComponent';
import RigidBodyComponent from '../components/RigidBodyComponent';
import ScriptComponent from '../components/ScriptComponent';
import ShadowComponent from '../components/ShadowComponent';
import SlowTimeComponent from '../components/SlowTimeComponent';
import SoundComponent from '../components/SoundComponent';
import SpriteComponent from '../components/SpriteComponent';
import SpriteStateComponent from '../components/SpriteStateComponent';
import TeleportComponent from '../components/TeleportComponent';
import TextLabelComponent from '../components/TextLabelComponent';
import TransformComponent from '../components/TransformComponent';

export type AnimationComponentType = InstanceType<typeof AnimationComponent>;
export type BoxColliderComponentType = InstanceType<typeof BoxColliderComponent>;
export type CameraFollowComponentType = InstanceType<typeof CameraFollowComponent>;
export type CameraShakeComponentType = InstanceType<typeof CameraShakeComponent>;
export type DamageRadiusComponentType = InstanceType<typeof DamageRadiusComponent>;
export type DeadBodyOnDeathComponentType = InstanceType<typeof DeadBodyOnDeathComponent>;
export type EntityDestinationComponentType = InstanceType<typeof EntityDestinationComponent>;
export type EntityEffectComponentType = InstanceType<typeof EntityEffectComponent>;
export type EntityFollowComponentType = InstanceType<typeof EntityFollowComponent>;
export type HealthComponentType = InstanceType<typeof HealthComponent>;
export type HighlightComponentType = InstanceType<typeof HighlightComponent>;
export type LifetimeComponentType = InstanceType<typeof LifetimeComponent>;
export type LightEmitComponentType = InstanceType<typeof LightEmitComponent>;
export type ParticleComponentType = InstanceType<typeof ParticleComponent>;
export type ParticleEmitComponentType = InstanceType<typeof ParticleEmitComponent>;
export type PlayerControlComponentType = InstanceType<typeof PlayerControlComponent>;
export type ProjectileComponentType = InstanceType<typeof ProjectileComponent>;
export type RangedAttackEmitterComponentType = InstanceType<typeof RangedAttackEmitterComponent>;
export type RigidBodyComponentType = InstanceType<typeof RigidBodyComponent>;
export type ScriptComponentType = InstanceType<typeof ScriptComponent>;
export type ShadowComponentType = InstanceType<typeof ShadowComponent>;
export type SlowTimeComponentType = InstanceType<typeof SlowTimeComponent>;
export type SoundComponentType = InstanceType<typeof SoundComponent>;
export type SpriteComponentType = InstanceType<typeof SpriteComponent>;
export type SpriteStateComponentType = InstanceType<typeof SpriteStateComponent>;
export type TeleportComponentType = InstanceType<typeof TeleportComponent>;
export type TextLabelComponentType = InstanceType<typeof TextLabelComponent>;
export type TransformComponentType = InstanceType<typeof TransformComponent>;

export type ComponentType = AnimationComponentType | BoxColliderComponentType | CameraFollowComponentType | CameraShakeComponentType | DamageRadiusComponentType | DeadBodyOnDeathComponentType | EntityDestinationComponentType | EntityEffectComponentType | EntityFollowComponentType | HealthComponentType | HighlightComponentType | LifetimeComponentType | LightEmitComponentType | ParticleComponentType | ParticleEmitComponentType | PlayerControlComponentType | ProjectileComponentType | RangedAttackEmitterComponentType | RigidBodyComponentType | ScriptComponentType | ShadowComponentType | SlowTimeComponentType | SoundComponentType | SpriteComponentType | SpriteStateComponentType | TeleportComponentType | TextLabelComponentType | TransformComponentType;
