import AnimationComponent from '../components/AnimationComponent';
import BoxColliderComponent from '../components/BoxColliderComponent';
import CameraFollowComponent from '../components/CameraFollowComponent';
import CameraShakeComponent from '../components/CameraShakeComponent';
import DamageRadiusComponent from '../components/DamageRadiusComponent';
import DeadBodyOnDeathComponent from '../components/DeadBodyOnDeathComponent';
import EntityDestinationComponent from '../components/EntityDestinationComponent';
import EntityEffectComponent from '../components/EntityEffectComponent';
import EntityFollowComponent from '../components/EntityFollowComponent';
import HealthComponent from '../components/HealthComponent';
import HighlightComponent from '../components/HighlightComponent';
import LifetimeComponent from '../components/LifetimeComponent';
import LightEmitComponent from '../components/LightEmitComponent';
import ParticleComponent from '../components/ParticleComponent';
import ParticleEmitComponent from '../components/ParticleEmitComponent';
import PlayerControlComponent from '../components/PlayerControlComponent';
import ProjectileComponent from '../components/ProjectileComponent';
import RangedAttackEmitterComponent from '../components/RangedAttackEmitterComponent';
import RigidBodyComponent from '../components/RigidBodyComponent';
import ScriptComponent from '../components/ScriptComponent';
import ShadowComponent from '../components/ShadowComponent';
import SlowTimeComponent from '../components/SlowTimeComponent';
import SoundComponent from '../components/SoundComponent';
import SpriteComponent from '../components/SpriteComponent';
import SpriteStateComponent from '../components/SpriteStateComponent';
import TeleportComponent from '../components/TeleportComponent';
import TextLabelComponent from '../components/TextLabelComponent';
import TransformComponent from '../components/TransformComponent';

type AnimationComponentType = InstanceType<typeof AnimationComponent>;
type BoxColliderComponentType = InstanceType<typeof BoxColliderComponent>;
type CameraFollowComponentType = InstanceType<typeof CameraFollowComponent>;
type CameraShakeComponentType = InstanceType<typeof CameraShakeComponent>;
type DamageRadiusComponentType = InstanceType<typeof DamageRadiusComponent>;
type DeadBodyOnDeathComponentType = InstanceType<typeof DeadBodyOnDeathComponent>;
type EntityDestinationComponentType = InstanceType<typeof EntityDestinationComponent>;
type EntityEffectComponentType = InstanceType<typeof EntityEffectComponent>;
type EntityFollowComponentType = InstanceType<typeof EntityFollowComponent>;
type HealthComponentType = InstanceType<typeof HealthComponent>;
type HighlightComponentType = InstanceType<typeof HighlightComponent>;
type LifetimeComponentType = InstanceType<typeof LifetimeComponent>;
type LightEmitComponentType = InstanceType<typeof LightEmitComponent>;
type ParticleComponentType = InstanceType<typeof ParticleComponent>;
type ParticleEmitComponentType = InstanceType<typeof ParticleEmitComponent>;
type PlayerControlComponentType = InstanceType<typeof PlayerControlComponent>;
type ProjectileComponentType = InstanceType<typeof ProjectileComponent>;
type RangedAttackEmitterComponentType = InstanceType<typeof RangedAttackEmitterComponent>;
type RigidBodyComponentType = InstanceType<typeof RigidBodyComponent>;
type ScriptComponentType = InstanceType<typeof ScriptComponent>;
type ShadowComponentType = InstanceType<typeof ShadowComponent>;
type SlowTimeComponentType = InstanceType<typeof SlowTimeComponent>;
type SoundComponentType = InstanceType<typeof SoundComponent>;
type SpriteComponentType = InstanceType<typeof SpriteComponent>;
type SpriteStateComponentType = InstanceType<typeof SpriteStateComponent>;
type TeleportComponentType = InstanceType<typeof TeleportComponent>;
type TextLabelComponentType = InstanceType<typeof TextLabelComponent>;
type TransformComponentType = InstanceType<typeof TransformComponent>;
